name: "GitHub Actions terraform"

on:
  workflow_call:
    inputs:
      kics-ignore:
        default: false
        type: boolean
        description: "ignore kics failure"
      kics-level-failure:
        default: "high,medium"
        type: string
        description: "kics level failure"
      working_directory:
        default: "terraform"
        type: string
        description: "Terraform working directory"
      wiz_policy:
        default: "Default IaC policy"
        type: string
        description: "policy to use with wiz"
    secrets:
      infracost_api_key:
        description: "Infracost api key"
        required: true
      LVMH_GITHUB_TOKEN:
        description: "Token for get token"
        required: true
      WIZ_CLIENT_ID:
        description: "Wiz Client ID sac"
      WIZ_CLIENT_SECRET:
        description: "Wiz Client Secret sac"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tf_dirs: ${{ steps.tf_list.outputs.tf_dirs }}
      live_tf_dirs: ${{ steps.tf_list.outputs.live_tf_dirs }}
    env:
      working_directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        if: github.event_name == 'pull_request'
        with:
          files: ${{ env.working_directory }}

      - name: List tf directories
        id: tf_list
        if: |
          steps.changed-files.outputs.any_changed == 'true' || github.event_name != 'pull_request'
        run: |
          if [ "${{ steps.changed-files.outputs.any_changed }}" == 'true' ]
          then
            dirs="$(for d in ${{ steps.changed-files-specific.outputs.all_changed_files }} ; do echo -n dirname $d ; done | sort -u)"
          else
            dirs="${{ env.working_directory }}"
          fi
          all_tf_dirs="$(find ${dirs} \
                             -name '*.tf' \
                             -not -path "*\.terraform*" \
                             -exec dirname {} \; | sort -u | jq -R | jq -scM )"
          live_tf_dirs="$(find ${dirs} \
                             -name '*.tf' \
                             -not -path "*modules*" \
                             -exec dirname {} \; | sort -u | jq -R | jq -scM )"
          echo "tf_dirs=${all_tf_dirs}" 
          echo "live_tf_dirs=${live_tf_dirs}"
          echo "tf_dirs=${all_tf_dirs}" >> $GITHUB_OUTPUT
          echo "live_tf_dirs=${live_tf_dirs}" >> $GITHUB_OUTPUT

  terraform-fmt:
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.tf_dirs != null
    env:
      working_directory: ${{ inputs.working_directory }}
    strategy:
      matrix:
        tf_dirs: ${{fromJson(needs.setup.outputs.tf_dirs)}}
    steps:
      - name: install tfenv
        run: |
          git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
          export PATH=$PATH:$HOME/.tfenv/bin
      - name: Checkout
        uses: actions/checkout@v3
      - name: fmt
        run: |
          cd ${{ matrix.tf_dirs }}
          terraform fmt --check

  terraform-lint:
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.tf_dirs != null
    env:
      working_directory: ${{ inputs.working_directory }}
    strategy:
      matrix:
        tf_dirs: ${{fromJson(needs.setup.outputs.live_tf_dirs)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: v0.43.0
      - name: Init TFLint
        run: |
          tflint --init
      - name: Run TFLint
        run: |
          cd ${{ matrix.tf_dirs }}
          tflint -f compact

  terraform-kics:
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.tf_dirs != null
    steps:
      - uses: actions/checkout@v3
      - name: run kics Scan
        uses: checkmarx/kics-github-action@v1.6
        continue-on-error: ${{ inputs.kics-ignore }}
        with:
          path: ${{ join(fromJson(needs.setup.outputs.tf_dirs)) }}
          output_path: myResults/
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on: ${{ inputs.kics-level-failure }}
          enable_comments: true
      - name: display kics results
        run: |
          cat myResults/results.json

  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    #needs: setup
    permissions:
      contents: read
      pull-requests: write
    env:
      working_directory: ${{ inputs.working_directory }}
      LVMH_GITHUB_TOKEN: ${{ secrets.LVMH_GITHUB_TOKEN }}
    # strategy:
    #   matrix:
    #     tf_dirs: ${{fromJson(needs.setup.outputs.live_tf_dirs)}}
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        # See https://github.com/infracost/actions/tree/master/setup for other inputs
        # If you can't use this action, see Docker images in https://infracost.io/cicd
        with:
          api-key: ${{ secrets.infracost_api_key }}

      - name: setup github config for private modules
        run: |
          git config \
            --global url."https://$LVMH_GITHUB_TOKEN@github.com".insteadOf https://github.com

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: "${{ github.event.pull_request.base.ref }}"

      # Generate Infracost JSON file as the baseline.
      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=${working_directory} \
                              --format=json \
                              --out-file=/tmp/infracost-base.json \
                    || export NO_BASE_TF=1 && export NO_BASE_TF=0

      # Checkout the current PR branch so we can create a diff.
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Generate Infracost report
        run: |
          if [ $NO_BASE_TF -eq 0 ]
          then
              infracost diff --path=${working_directory} \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json
          else
              infracost breakdown --path=${working_directory}
          fi
      - name: Post Infracost comment
        if: github.event_name == 'pull_request'
        run: |
          infracost comment github --path=/tmp/infracost.json \
                                   --repo=$GITHUB_REPOSITORY \
                                   --github-token=${{github.token}} \
                                   --pull-request=${{github.event.pull_request.number}} \
                                   --behavior=update

  wiz-cli-iac-scan:
    name: "Wiz-cli IaC Scan"
    runs-on: ubuntu-latest
    env:
      SCAN_PATH: ${{ inputs.working_directory }}
      POLICY: ${{ inputs.wiz_policy }}
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Check out repository
        uses: actions/checkout@v2
        if: ${{ env.WIZ_CLIENT_ID != null }}

      - name: Download Wiz-cli
        run: curl -o wizcli https://wizcli.app.wiz.io/wizcli && chmod +x wizcli
        if: ${{ env.WIZ_CLIENT_ID != null }}

      - name: Authenticate to Wiz
        run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
        if: ${{ env.WIZ_CLIENT_ID != null }}

      - name: Run wiz-cli IaC scan
        run: ./wizcli iac scan --path $SCAN_PATH --policy "$POLICY"
        if: ${{ env.WIZ_CLIENT_ID != null }}
